name: umyra
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Rest API and State management
  flutter_bloc: ^8.0.0
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  dio: ^4.0.0
  provider: ^6.0.2
  get_it: ^7.2.0

  # Local Storage
  path_provider: ^2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  l: ^3.1.0
  pedantic: ^1.10.0
  connectivity_plus: ^2.3.0
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.12
  image_picker: ^0.8.4+5
  image_cropper: ^3.0.0
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_route: ^5.0.1
  platform_info: ^3.1.0
  dropdown_button2: ^1.8.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.0
  dropdown_textfield: ^1.0.8
  figma_squircle: ^0.5.3
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any
  json_serializable: ^6.0.1
  auto_route_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
